config_name: 'resmlp'

## Setup
n_doors: 50
turns: 1000
door_decay : 0.97

## Model config
model_name: ResMLP
hidden_units: 512
n_layers : 3
dropout_rate: 0.1

## Training
lr: 0.01
batch_size: 16
num_episodes: 10_000
epsilon_decay: .999
